version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: \
        ${POSTGRES_DB:-roundtable}
      POSTGRES_USER: \
        ${POSTGRES_USER:-roundtable}
      POSTGRES_PASSWORD: \
        ${POSTGRES_PASSWORD:-roundtablepwd}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn core.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  worker:
    build: .
    command: celery -A worker.celery_app worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - api
      - redis

  bot:
    build: .
    command: python -m bot.runner
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    depends_on:
      - api
      - redis

volumes:
  postgres_data:
