version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: runtime
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
      target: runtime
    command: python bot.py
    env_file:
      - .env
    depends_on:
      - api
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
      target: runtime
    command: celery -A worker.celery_app worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: roundtable
      POSTGRES_USER: roundtable
      POSTGRES_PASSWORD: roundtablepwd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
