version: '3.9'

services:
  api:
    build: .
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  bot:
    build: .
    command: python -m bot.main
    env_file: .env
    depends_on:
      - api

  worker:
    build: .
    command: celery -A worker.celery_app worker --loglevel=INFO
    env_file: .env
    depends_on:
      - redis
      - db

  db:
    image: postgres:14
    environment:
      POSTGRES_DB: roundtable
      POSTGRES_USER: roundtable
      POSTGRES_PASSWORD: roundtablepwd
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"

