[build-system]
requires = ["setuptools>=63", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = [
    "bot*",
    "core*",
    "adapters*",
    "admin*",
    "orchestrator*",
    "worker*",
]

[project]
name = "roundtable"
version = "0.1.0"
description = "Roundtable AI discussion orchestrator"
authors = [{name = "Roundtable"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.111.0",
    "uvicorn[standard]>=0.30.0",
    "sqlalchemy[asyncio]>=2.0.30",
    "aiosqlite>=0.20.0",
    "asyncpg>=0.29.0",
    "alembic>=1.13.1",
    "pydantic>=2.6.4",
    "pydantic-settings>=2.1.0",
    "aiogram>=3.4.1",
    "redis>=5.0.4",
    "celery[redis]>=5.3.6",
    "python-dotenv>=1.0.1",
    "httpx>=0.27.0",
    "jinja2>=3.1.4",
    "itsdangerous>=2.2.0",
    "cryptography>=42.0.5",
    "tenacity>=8.2.3"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0",
    "pytest-asyncio>=0.23.7",
    "pytest-mock>=3.12.0",
    "httpx[http2]>=0.27.0",
    "ruff>=0.4.2",
    "black>=24.3.0"
]

[tool.black]
line-length = 100
target-version = ["py311"]

[tool.ruff]
line-length = 100
select = ["E", "F", "I", "UP", "B", "S", "A"]
ignore = ["E501"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
addopts = "-q"

